<?php

use Illuminate\Database\Seeder;

class InvestmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('investments')->delete();
        
        \DB::table('investments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'amc_id' => 1,
                'risklevel' => 1,
                'registered_date' => '2017-04-13',
                'Investment_policy' => 'Investment_policy',
                'assetvalue' => 1,
                'trustee' => 'trustee',
                'frequency' => 'frequency',
                'name' => 'funds 1',
                'desc' => 'lastname',
                'company_name' => 'company_name',
                'paymentpolicy' => 1,
                'type' => 1,
                'aimcfundtype' => 1,
                'period' => 'period',
                'assetinvest' => 'assetinvest',
                'strategy' => 'strategy',
                'factorimpact' => 'factorimpact',
                'investertype' => 'investertype',
                'benchmarkdetail' => 'benchmarkdetail',
                'stock' => 1.0,
                'bond' => 1.0,
                'cash' => 1.0,
                'assetother' => 1.0,
                'fund_start' => '2017-04-13',
                'fund_end' => '2017-04-13',
                'created_at' => '2017-04-13 07:26:55',
                'updated_at' => '2017-04-13 07:26:55',
            ),
            1 => 
            array (
                'id' => 2,
                'amc_id' => 2,
                'risklevel' => 2,
                'registered_date' => '2017-04-13',
                'Investment_policy' => 'Investment_policy',
                'assetvalue' => 1,
                'trustee' => 'trustee',
                'frequency' => 'frequency',
                'name' => 'funds 2',
                'desc' => 'lastname',
                'company_name' => 'company_name2',
                'paymentpolicy' => 1,
                'type' => 1,
                'aimcfundtype' => 1,
                'period' => 'period',
                'assetinvest' => 'assetinvest',
                'strategy' => 'strategy',
                'factorimpact' => 'factorimpact',
                'investertype' => 'investertype',
                'benchmarkdetail' => 'benchmarkdetail',
                'stock' => 1.0,
                'bond' => 1.0,
                'cash' => 1.0,
                'assetother' => 1.0,
                'fund_start' => '2017-04-13',
                'fund_end' => '2017-04-13',
                'created_at' => '2017-04-13 07:26:55',
                'updated_at' => '2017-04-13 07:26:55',
            ),
            2 => 
            array (
                'id' => 3,
                'amc_id' => 3,
                'risklevel' => 3,
                'registered_date' => '2017-04-13',
                'Investment_policy' => 'Investment_policy',
                'assetvalue' => 1,
                'trustee' => 'trustee',
                'frequency' => 'frequency',
                'name' => 'funds 3',
                'desc' => 'lastname',
                'company_name' => 'company_name3',
                'paymentpolicy' => 1,
                'type' => 1,
                'aimcfundtype' => 1,
                'period' => 'period',
                'assetinvest' => 'assetinvest',
                'strategy' => 'strategy',
                'factorimpact' => 'factorimpact',
                'investertype' => 'investertype',
                'benchmarkdetail' => 'benchmarkdetail',
                'stock' => 1.0,
                'bond' => 1.0,
                'cash' => 1.0,
                'assetother' => 1.0,
                'fund_start' => '2017-04-13',
                'fund_end' => '2017-04-13',
                'created_at' => '2017-04-13 07:26:55',
                'updated_at' => '2017-04-13 07:26:55',
            ),
            3 => 
            array (
                'id' => 4,
                'amc_id' => 1,
                'risklevel' => 4,
                'registered_date' => '2017-04-13',
                'Investment_policy' => 'Investment_policy',
                'assetvalue' => 1,
                'trustee' => 'trustee',
                'frequency' => 'frequency',
                'name' => 'funds 4',
                'desc' => 'lastname',
                'company_name' => 'company_name',
                'paymentpolicy' => 1,
                'type' => 1,
                'aimcfundtype' => 1,
                'period' => 'period',
                'assetinvest' => 'assetinvest',
                'strategy' => 'strategy',
                'factorimpact' => 'factorimpact',
                'investertype' => 'investertype',
                'benchmarkdetail' => 'benchmarkdetail',
                'stock' => 1.0,
                'bond' => 1.0,
                'cash' => 1.0,
                'assetother' => 1.0,
                'fund_start' => '2017-04-13',
                'fund_end' => '2017-04-13',
                'created_at' => '2017-04-13 07:26:55',
                'updated_at' => '2017-04-13 07:26:55',
            ),
            4 => 
            array (
                'id' => 5,
                'amc_id' => 1,
                'risklevel' => 4,
                'registered_date' => '2017-04-13',
                'Investment_policy' => 'Investment_policy',
                'assetvalue' => 1,
                'trustee' => 'trustee',
                'frequency' => 'frequency',
                'name' => 'funds 4',
                'desc' => 'lastname',
                'company_name' => 'company_name',
                'paymentpolicy' => 1,
                'type' => 1,
                'aimcfundtype' => 1,
                'period' => 'period',
                'assetinvest' => 'assetinvest',
                'strategy' => 'strategy',
                'factorimpact' => 'factorimpact',
                'investertype' => 'investertype',
                'benchmarkdetail' => 'benchmarkdetail',
                'stock' => 1.0,
                'bond' => 1.0,
                'cash' => 1.0,
                'assetother' => 1.0,
                'fund_start' => '2017-04-13',
                'fund_end' => '2017-04-13',
                'created_at' => '2017-04-13 07:26:55',
                'updated_at' => '2017-04-13 07:26:55',
            ),
        ));
        
        
    }
}